package edu.uams.clara.webapp.common.domain.usercontext.enums;

import java.io.Serializable;

import org.springframework.security.core.GrantedAuthority;

public enum Permission implements Serializable, GrantedAuthority {

	ROLE_PI, ROLE_GATEKEEPER, ROLE_IRB_PREREVIEW, ROLE_IRB_OFFICE,ROLE_IRB_EXPEDITED_REVIEWER, ROLE_IRB_EXEMPT_REVIEWER,
	ROLE_BUDGET_MANAGER, ROLE_BUDGET_DEVELOPER, ROLE_BUDGET_REVIEWER, ROLE_COVERAGE_REVIEWER, ROLE_COVERAGE_MANAGER, ROLE_BIOSAFETY_REVIEWER,
	ROLE_MONITORING_REGULATORY_QA_REVIEWER,ROLE_HOSPITAL_SERVICES_REVIEWER,
	ROLE_SUB_DEPARTMENT_CHIEF, ROLE_DEPARTMENT_CHAIR, ROLE_COLLEGE_DEAN,
	ROLE_SECRET_ADMIN,
	ROLE_IRB_REVIEWER, ROLE_SYSTEM_ADMIN,
	ROLE_PHARMACY_REVIEW,
	ROLE_IRB_CONSENT_REVIEWER,
	ROLE_IRB_PROTOCOL_REVIEWER,
	ROLE_IRB_CHAIR,
	ROLE_REGULATORY_MANAGER,
	ROLE_DEPARTMENT_ADMIN,
	//ROLE_LEGAL_REVIEWER,
	ROLE_CONTRACT_MANAGER,
	ROLE_CONTRACT_ADMIN,
	ROLE_CONTRACT_LEGAL_REVIEW,
	ROLE_PROTOCOL_LEGAL_REVIEW,
	ROLE_PRMC_REVIEWER,
	ROLE_RADIATION_SAFETY_REVIEWER,
	ROLE_BEACON_TEAM,
	ROLE_PRECOVERAGE_REVIEWER,
	ROLE_WILLOW_TEAM,
	ROLE_COI_REVIEWER,
	ROLE_ACHRI_REVIEWER,
	ROLE_REVIEWER,
	ROLE_CCTO,
	ROLE_RESEARCH_COMPLIANCE,
	VIEW_ALL_STUDY,
	VIEW_STUDY, EDIT_STUDY, VIEW_BUDGET_PRICE, VIEW_BUDGET_COST, VIEW_BUDGET, EDIT_BUDGET, EDIT_LOCKED_BUDGET, LOCK_BUDGET, ROLE_PTL, VIEW_BUDGET_DOCUMENTS,
	COMMENT_CAN_MOVE, COMMENT_CAN_COPY,
	DELETE_DOCUMENT,
	DELETE_FORM_ANY_TIME,
	CAN_EDIT_IRB_COMMENT_STATUS,
	EDIT_PROTOCOL_BASIC, EDIT_DRUGS_AND_DEVICES, EDIT_IRB_DETERMINATION, EDIT_COVERAGE_DETERMINATION, EDIT_CONTRACT_BASIC, CANCEL_CONTRACT_FORM, ROLE_COMPLIANCE_REVIEW, ROLE_CLINICAL_TRIALS_REVIEW, EDIT_AGENDA,
	ROLE_IRB_ASSIGNER, FORWARD_CONTRACT, VIEW_AGENDA_ITEM, ROLE_IRB_MEETING_OPERATOR, COMMENT_CAN_ADD, HAVE_CHECKLIST, CREATE_NEW_FORM_ANYTIME, PUSH_TO_PSC, CONTINGENCY_CAN_ADD, EDIT_IRB_FEE, CAN_SEND_IRB_LETTER,
	EDIT_HOSPITAL_SERVICE_DETERMINATION, ROLE_ACH_PHARMACY_REVIEWER, VIEW_BUDGET_OTHER_PROCEDURE_CODES, CAN_UPLOAD_DOCUMENT, EDIT_REPORTS, DELETE_CONTRACT_DOCUMENT, VIEW_AGENDA_ONLY, EDIT_ENROLLMENT_DATE, EDIT_PHARMACY, VIEW_ALL_CONTRACT, ROLE_PBS,EDIT_PBS, PUSH_TO_EPIC, DELETE_BUDGET,
	VIEW_IRB_COMMENTS, DELETE_CONTRACT_FORM_ANY_TIME, EDIT_CLINICAL_TRIALS,CAN_CREATE_CONTRACT, CAN_UPLOAD_CONTRACT_DOCUMENT_AT_ANYTIME, CAN_EXECUTE_CONTRACT_AT_ANYTIME, CANCEL_PROTOCOL_FORM, VIEW_STAFF_SALARY, VIEW_COM_CONTRACT, CAN_UPLOAD_FINAL_LEGAL_APPROVAL_CONSENT, CAN_ONLY_VIEW_APPROVED_AGENDA,
	CAN_REORDER_COMMENTS;
	
	@Override
	public String getAuthority() {		
		return this.toString();
	}
}
