package edu.uams.clara.webapp.protocol.domain.protocolform.enums;

public enum ProtocolFormXmlDataType {
	COMMITTEE_ASSIGNMENT_QUEUE,
	IRB_REVIEWER_EXPEDITED_REVIEW,
	IRB_REVIEWER_REVIEW,
	IRB_OFFICE_EXEMPT_REVIEW,
	HSRD_IRB_OFFICE_REVIEW_FORM,
	REPORTABLE_NEW_INFORMATION_IRB_OFFICE_REVIEW_FORM,
	STUDY_CLOSURE_IRB_OFFICE_REVIEW_FORM,
	PROTOCOL, BUDGET, NEW_SUBMISSION, 
	HUMAN_SUBJECT_RESEARCH_DETERMINATION, 
	HUMANITARIAN_USE_DEVICE, 
	EMERGENCY_USE, 
	RESPONSE, 
	MODIFICATION, 
	CONTINUING_REVIEW, 
	REPORTABLE_NEW_INFORMATION, 
	DEATH_REPORT, 
	STUDY_CLOSURE, 
	PHARMACY, 
	HUMANITARIAN_USE_DEVICE_RENEWAL, 
	AUDIT, 
	ARCHIVE, 
	STAFF, 
	PRIVACY_BOARD,
	STUDY_RESUMPTION;
}
